import type { Config } from 'tailwindcss';
import colors from 'tailwindcss/colors';
import { fontFamily } from 'tailwindcss/defaultTheme';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safeList: [
    'bg-red-500',
    'bg-green-500',
    'bg-blue-500',
    'bg-blue-400',
    'bg-yellow-500',
    'bg-purple-400',
    'bg-orange-500',
    'bg-teal-400',
    'bg-indigo-400',
    'bg-gray-500',
    'bg-emerald-300',
    'bg-fuchsia-400',
    'bg-cyan-400',
    'bg-rose-400',
    'bg-lime-600',
    'bg-green-400',
    'bg-amber-700',
    'bg-violet-500',
    'bg-orange-300',
    'bg-cyan-600',
    'bg-violet-300',
    'bg-emerald-600',
    'bg-sky-700',
    'bg-stone-400',
    'bg-teal-700',
    'bg-red-800',
    'bg-orange-700',
    'bg-amber-500',
    'bg-lime-800',
    'bg-teal-900',
    'bg-sky-900',
    'bg-fuchsia-700',
    'bg-pink-700',
    'bg-green-800',
    'bg-rose-600',
    'bg-blue-800',
    'bg-blue-700',
    'bg-cyan-800',
    'bg-indigo-600',
    'bg-purple-900',
    'bg-yellow-600',
    'bg-blue-900',
    'bg-gray-600',
    'bg-slate-400',
    'bg-stone-700',
    'bg-sky-600',
    'bg-red-400',
    'bg-indigo-800',
    'bg-pink-900',
    'bg-amber-400',
    'bg-gray-700',
    'bg-yellow-400',
    'bg-amber-600',
    'bg-indigo-500',
    'bg-purple-600',
    'bg-green-300',
    'bg-blue-300',
    'bg-rose-500',
    'bg-blue-600',
    'bg-fuchsia-500',
    'bg-rose-700',
    'bg-orange-600',
    'bg-blue-900',
    'bg-orange-900',
    'bg-gray-800',
    'bg-pink-500',
    'bg-lime-700',
    'bg-violet-700',
    'bg-green-600',
    'bg-teal-500',
    'bg-sky-500',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      screens: {
        xs: '480px',
        pwa: { raw: '(display-mode: fullscreen)' },
      },
      fontFamily: {
        sans: ['var(--font-sans)', ...fontFamily.sans],
        header: ['Space Grotesk', 'sans-serif'],
      },
      colors: {
        link: colors.blue[500],
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
