import '@fontsource/space-grotesk/400.css'; // Specify weight
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';

import './globals.css';

import Footer from '@/components/Site/Footer';
import Header from '@/components/Site/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider>
          <div className='flex min-h-screen flex-col'>
            <Header />
            <div className='flex-grow justify-center items-center max-w-xl mx-auto'>{children}</div>
            <Footer />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
