import {
  IconAffiliate,
  IconBabyCarriage,
  IconBed,
  IconBook,
  IconBook2,
  IconBrain,
  IconBrandLeetcode,
  IconBrush,
  IconBug,
  IconBuilding,
  IconBuildingLighthouse,
  IconBuildingStore,
  IconBulb,
  IconCalendar,
  IconChevronsUp,
  IconClipboardList,
  IconCode,
  IconCompass,
  IconConfetti,
  IconCup,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDog,
  IconEar,
  IconEdit,
  IconEye,
  IconFireExtinguisher,
  IconFirstAidKit,
  IconFlask,
  IconFrame,
  IconHammer,
  IconHeart,
  IconHearts,
  IconListDetails,
  IconListTree,
  IconMap,
  IconMicrophone,
  IconMoodHappy,
  IconMusic,
  IconPlane,
  IconPray,
  IconProgress,
  IconQuestionMark,
  IconRocket,
  IconRun,
  IconScale,
  IconSchool,
  IconSearch,
  IconShoppingBag,
  IconSofa,
  IconSoup,
  IconSunrise,
  IconTool,
  IconTrees,
  IconTriangle,
  IconTypography,
  IconUser,
  IconUserSearch,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconWashMachine,
  IconZzz,
} from '@tabler/icons-react';

import { UserStatusConfig } from '@/lib/types';

export type TablerIcon = typeof IconBed;

export const userStatusConfig: UserStatusConfig = {
  offline: { textColor: 'text-gray-500', backgroundColor: 'bg-gray-500', nonSelectable: true },
  online: { textColor: 'text-green-500', backgroundColor: 'bg-green-500', icon: IconUser },
  admin: { textColor: 'text-amber-700', backgroundColor: 'bg-amber-700', icon: IconListDetails },
  analyzing: {
    textColor: 'text-cyan-800',
    backgroundColor: 'bg-cyan-800',
    icon: IconSearch,
  },
  awaking: { textColor: 'text-amber-500', backgroundColor: 'bg-amber-500', icon: IconSunrise },
  brainstorming: { textColor: 'text-blue-600', backgroundColor: 'bg-blue-600', icon: IconBulb },
  building: { textColor: 'text-green-800', backgroundColor: 'bg-green-800', icon: IconBuilding },
  busying: {
    textColor: 'text-indigo-400',
    backgroundColor: 'bg-indigo-400',
    icon: IconClipboardList,
  },
  chores: {
    textColor: 'text-slate-400',
    backgroundColor: 'bg-slate-400',
    icon: IconWashMachine,
  },
  coding: { textColor: 'text-violet-300', backgroundColor: 'bg-violet-300', icon: IconCode },
  curating: { textColor: 'text-rose-500', backgroundColor: 'bg-rose-500', icon: IconUserSearch },
  creating: { textColor: 'text-yellow-500', backgroundColor: 'bg-yellow-500', icon: IconTool },
  debugging: {
    textColor: 'text-gray-600',
    backgroundColor: 'bg-gray-600',
    icon: IconBug,
  },
  designing: { textColor: 'text-stone-400', backgroundColor: 'bg-stone-400', icon: IconFrame },
  drinking: { textColor: 'text-blue-500', backgroundColor: 'bg-blue-500', icon: IconCup },
  editing: { textColor: 'text-blue-300', backgroundColor: 'bg-blue-300', icon: IconEdit },
  enjoying: {
    textColor: 'text-emerald-300',
    backgroundColor: 'bg-emerald-300',
    icon: IconMoodHappy,
  },
  errands: {
    textColor: 'text-stone-700',
    backgroundColor: 'bg-stone-400',
    icon: IconBuildingStore,
  },
  exercising: { textColor: 'text-blue-400', backgroundColor: 'bg-blue-400', icon: IconRun },
  exploring: { textColor: 'text-green-300', backgroundColor: 'bg-green-300', icon: IconMap },
  fixing: { textColor: 'text-red-800', backgroundColor: 'bg-red-800', icon: IconFireExtinguisher },
  filming: { textColor: 'text-pink-700', backgroundColor: 'bg-pink-700', icon: IconVideo },
  focusing: { textColor: 'text-pink-400', backgroundColor: 'bg-pink-400', icon: IconBrain },
  food: { textColor: 'text-teal-400', backgroundColor: 'bg-teal-400', icon: IconSoup },
  gaming: {
    textColor: 'text-purple-400',
    backgroundColor: 'bg-purple-400',
    icon: IconDeviceGamepad2,
  },
  hobbying: { textColor: 'text-emerald-600', backgroundColor: 'bg-emerald-600', icon: IconBrush },
  learning: { textColor: 'text-lime-600', backgroundColor: 'bg-lime-600', icon: IconBook2 },
  listening: { textColor: 'text-pink-900', backgroundColor: 'bg-pink-900', icon: IconEar },
  maintaining: { textColor: 'text-amber-500', backgroundColor: 'bg-amber-500', icon: IconHammer },
  managing: { textColor: 'text-orange-300', backgroundColor: 'bg-orange-300', icon: IconTriangle },
  meeting: { textColor: 'text-blue-500', backgroundColor: 'bg-blue-500', icon: IconUsers },
  mentoring: {
    textColor: 'text-purple-600',
    backgroundColor: 'bg-purple-600',
    icon: IconBuildingLighthouse,
  },
  networking: {
    textColor: 'text-indigo-500',
    backgroundColor: 'bg-indigo-500',
    icon: IconAffiliate,
  },
  outside: { textColor: 'text-green-400', backgroundColor: 'bg-green-400', icon: IconTrees },
  optimising: { textColor: 'text-lime-800', backgroundColor: 'bg-lime-800', icon: IconChevronsUp },
  organising: {
    textColor: 'text-red-400',
    backgroundColor: 'bg-red-400',
    icon: IconListTree,
  },
  parenting: { textColor: 'text-sky-900', backgroundColor: 'bg-sky-900', icon: IconBabyCarriage },
  partner: { textColor: 'text-rose-600', backgroundColor: 'bg-rose-600', icon: IconHearts },
  partying: { textColor: 'text-violet-500', backgroundColor: 'bg-violet-500', icon: IconConfetti },
  performing: {
    textColor: 'text-teal-900',
    backgroundColor: 'bg-teal-900',
    icon: IconMusic,
  },
  pets: { textColor: 'text-amber-600', backgroundColor: 'bg-amber-600', icon: IconDog },
  practicing: {
    textColor: 'text-yellow-400',
    backgroundColor: 'bg-yellow-400',
    icon: IconBrandLeetcode,
  },
  planning: { textColor: 'text-lime-500', backgroundColor: 'bg-lime-500', icon: IconCalendar },
  procrastinating: {
    textColor: 'text-cyan-600',
    backgroundColor: 'bg-cyan-600',
    icon: IconQuestionMark,
  },
  reading: { textColor: 'text-sky-600', backgroundColor: 'bg-sky-600', icon: IconBook },
  recording: {
    textColor: 'text-fuchsia-700',
    backgroundColor: 'bg-fuchsia-700',
    icon: IconMicrophone,
  },
  relaxing: { textColor: 'text-orange-500', backgroundColor: 'bg-orange-500', icon: IconSofa },
  releasing: { textColor: 'text-blue-700', backgroundColor: 'bg-blue-700', icon: IconRocket },
  researching: { textColor: 'text-blue-900', backgroundColor: 'bg-blue-900', icon: IconCompass },
  resting: { textColor: 'text-fuchsia-500', backgroundColor: 'bg-fuchsia-500', icon: IconZzz },
  reviewing: { textColor: 'text-indigo-600', backgroundColor: 'bg-indigo-600', icon: IconScale },
  sciencing: { textColor: 'text-purple-900', backgroundColor: 'bg-purple-900', icon: IconFlask },
  scrolling: { textColor: 'text-gray-700', backgroundColor: 'bg-gray-700', icon: IconDeviceMobile },
  selfcare: { textColor: 'text-rose-400', backgroundColor: 'bg-rose-400', icon: IconHeart },
  shopping: { textColor: 'text-teal-700', backgroundColor: 'bg-teal-700', icon: IconShoppingBag },
  sleeping: { textColor: 'text-indigo-400', backgroundColor: 'bg-indigo-400', icon: IconBed },
  socialising: {
    textColor: 'text-fuchsia-400',
    backgroundColor: 'bg-fuchsia-400',
    icon: IconUsersGroup,
  },
  streaming: { textColor: 'text-purple-700', backgroundColor: 'bg-purple-700', icon: IconVideo },
  teaching: { textColor: 'text-cyan-400', backgroundColor: 'bg-cyan-400', icon: IconSchool },
  travelling: { textColor: 'text-sky-400', backgroundColor: 'bg-sky-400', icon: IconPlane },
  trying: { textColor: 'text-yellow-600', backgroundColor: 'bg-yellow-600', icon: IconProgress },
  volunteering: {
    textColor: 'text-amber-400',
    backgroundColor: 'bg-amber-400',
    icon: IconFirstAidKit,
  },
  watching: { textColor: 'text-indigo-800', backgroundColor: 'bg-indigo-800', icon: IconEye },
  working: { textColor: 'text-red-500', backgroundColor: 'bg-red-500', icon: IconDeviceLaptop },
  worshipping: { textColor: 'text-sky-700', backgroundColor: 'bg-sky-700', icon: IconPray },
  writing: { textColor: 'text-orange-700', backgroundColor: 'bg-orange-700', icon: IconTypography },
} as const;
export const userStatusOptions = Object.keys(userStatusConfig);
export const userSelectableStatusOptions = userStatusOptions.filter(
  (status) => !userStatusConfig[status as keyof UserStatusConfig].nonSelectable
);
